/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildWebAppsRouteImport } from './routes/build-web-apps'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as PageSlugRouteImport } from './routes/page.$slug'
import { Route as ApiAssetIdRouteImport } from './routes/api/asset.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicWaTokenRouteImport } from './routes/api/public/wa/token'
import { Route as ApiPublicWaWebappRouteImport } from './routes/api/public/wa/webapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildWebAppsRoute = BuildWebAppsRouteImport.update({
  id: '/build-web-apps',
  path: '/build-web-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/page/$slug',
  path: '/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetIdRoute = ApiAssetIdRouteImport.update({
  id: '/api/asset/$id',
  path: '/api/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaTokenRoute = ApiPublicWaTokenRouteImport.update({
  id: '/api/public/wa/token',
  path: '/api/public/wa/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaWebappRoute = ApiPublicWaWebappRouteImport.update({
  id: '/api/public/wa/webapp',
  path: '/api/public/wa/webapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build-web-apps': typeof BuildWebAppsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/page/$slug': typeof PageSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/wa/token': typeof ApiPublicWaTokenRoute
  '/api/public/wa/webapp': typeof ApiPublicWaWebappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build-web-apps': typeof BuildWebAppsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/page/$slug': typeof PageSlugRoute
  '/checkout': typeof CheckoutIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/wa/token': typeof ApiPublicWaTokenRoute
  '/api/public/wa/webapp': typeof ApiPublicWaWebappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build-web-apps': typeof BuildWebAppsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/page/$slug': typeof PageSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/wa/token': typeof ApiPublicWaTokenRoute
  '/api/public/wa/webapp': typeof ApiPublicWaWebappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build-web-apps'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/checkout/success'
    | '/page/$slug'
    | '/checkout/'
    | '/api/asset/$id'
    | '/api/public/health'
    | '/api/public/wa/token'
    | '/api/public/wa/webapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build-web-apps'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/checkout/success'
    | '/page/$slug'
    | '/checkout'
    | '/api/asset/$id'
    | '/api/public/health'
    | '/api/public/wa/token'
    | '/api/public/wa/webapp'
  id:
    | '__root__'
    | '/'
    | '/build-web-apps'
    | '/cart'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/checkout/success'
    | '/page/$slug'
    | '/checkout/'
    | '/api/asset/$id'
    | '/api/public/health'
    | '/api/public/wa/token'
    | '/api/public/wa/webapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildWebAppsRoute: typeof BuildWebAppsRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  PageSlugRoute: typeof PageSlugRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ApiAssetIdRoute: typeof ApiAssetIdRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicWaTokenRoute: typeof ApiPublicWaTokenRoute
  ApiPublicWaWebappRoute: typeof ApiPublicWaWebappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-web-apps': {
      id: '/build-web-apps'
      path: '/build-web-apps'
      fullPath: '/build-web-apps'
      preLoaderRoute: typeof BuildWebAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$slug': {
      id: '/page/$slug'
      path: '/page/$slug'
      fullPath: '/page/$slug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$id': {
      id: '/api/asset/$id'
      path: '/api/asset/$id'
      fullPath: '/api/asset/$id'
      preLoaderRoute: typeof ApiAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/token': {
      id: '/api/public/wa/token'
      path: '/api/public/wa/token'
      fullPath: '/api/public/wa/token'
      preLoaderRoute: typeof ApiPublicWaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/webapp': {
      id: '/api/public/wa/webapp'
      path: '/api/public/wa/webapp'
      fullPath: '/api/public/wa/webapp'
      preLoaderRoute: typeof ApiPublicWaWebappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildWebAppsRoute: BuildWebAppsRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  PageSlugRoute: PageSlugRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ApiAssetIdRoute: ApiAssetIdRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicWaTokenRoute: ApiPublicWaTokenRoute,
  ApiPublicWaWebappRoute: ApiPublicWaWebappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
