/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as ApiPublicCacheBustRouteImport } from './routes/api/public/cache-bust'
import { Route as ApiPublicCacheStatusRouteImport } from './routes/api/public/cache-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCacheBustRoute = ApiPublicCacheBustRouteImport.update({
  id: '/api/public/cache-bust',
  path: '/api/public/cache-bust',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCacheStatusRoute = ApiPublicCacheStatusRouteImport.update({
  id: '/api/public/cache-status',
  path: '/api/public/cache-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/api/media': typeof ApiMediaRoute
  '/post/$slug': typeof PostSlugRoute
  '/api/public/cache-bust': typeof ApiPublicCacheBustRoute
  '/api/public/cache-status': typeof ApiPublicCacheStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/api/media': typeof ApiMediaRoute
  '/post/$slug': typeof PostSlugRoute
  '/api/public/cache-bust': typeof ApiPublicCacheBustRoute
  '/api/public/cache-status': typeof ApiPublicCacheStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/api/media': typeof ApiMediaRoute
  '/post/$slug': typeof PostSlugRoute
  '/api/public/cache-bust': typeof ApiPublicCacheBustRoute
  '/api/public/cache-status': typeof ApiPublicCacheStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/api/media'
    | '/post/$slug'
    | '/api/public/cache-bust'
    | '/api/public/cache-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/api/media'
    | '/post/$slug'
    | '/api/public/cache-bust'
    | '/api/public/cache-status'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/api/media'
    | '/post/$slug'
    | '/api/public/cache-bust'
    | '/api/public/cache-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ApiMediaRoute: typeof ApiMediaRoute
  PostSlugRoute: typeof PostSlugRoute
  ApiPublicCacheBustRoute: typeof ApiPublicCacheBustRoute
  ApiPublicCacheStatusRoute: typeof ApiPublicCacheStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cache-bust': {
      id: '/api/public/cache-bust'
      path: '/api/public/cache-bust'
      fullPath: '/api/public/cache-bust'
      preLoaderRoute: typeof ApiPublicCacheBustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cache-status': {
      id: '/api/public/cache-status'
      path: '/api/public/cache-status'
      fullPath: '/api/public/cache-status'
      preLoaderRoute: typeof ApiPublicCacheStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ApiMediaRoute: ApiMediaRoute,
  PostSlugRoute: PostSlugRoute,
  ApiPublicCacheBustRoute: ApiPublicCacheBustRoute,
  ApiPublicCacheStatusRoute: ApiPublicCacheStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
